import { z } from "zod";

export const createCharacterSchema = z.object({
  projectId: z.string().min(1),
  name: z.string().min(1, "角色名不能为空").max(100),
  aliases: z.string().optional(),
  gender: z.string().optional(),
  apparentAge: z.number().int().positive().optional().nullable(),
  actualAge: z.number().int().positive().optional().nullable(),
  birthday: z.string().optional(),
  species: z.string().optional(),
  nationality: z.string().optional(),
  occupations: z.string().optional(),
  socialClass: z.string().optional(),
  characterStatus: z.enum(["ALIVE", "DEAD", "MISSING", "PRESUMED_DEAD"]).optional(),
  // 外貌
  height: z.string().optional(),
  build: z.string().optional(),
  skinTone: z.string().optional(),
  hairColor: z.string().optional(),
  hairStyle: z.string().optional(),
  eyeColor: z.string().optional(),
  distinguishingFeatures: z.string().optional(),
  appearanceDesc: z.string().optional(),
  // 性格
  personalityType: z.string().optional(),
  coreTraits: z.string().optional(),
  virtues: z.string().optional(),
  flaws: z.string().optional(),
  moralAlignment: z.string().optional(),
  // 背景
  childhood: z.string().optional(),
  familyBackground: z.string().optional(),
  traumas: z.string().optional(),
  secrets: z.string().optional(),
  // 语言习惯
  speechDialect: z.string().optional(),
  catchphrases: z.string().optional(),
  nervousHabits: z.string().optional(),
  hobbies: z.string().optional(),
  // 角色弧光
  arcType: z.string().optional(),
  arcStartState: z.string().optional(),
  arcMidpoint: z.string().optional(),
  arcEndState: z.string().optional(),
  developmentStatus: z.enum(["CONCEPT", "DEVELOPING", "FLESHED_OUT", "REVISING"]).optional(),
  // 元数据
  roleInStory: z.string().optional(),
  tags: z.string().optional(),
  groups: z.string().optional(),
  importance: z.number().int().min(1).max(10).optional(),
  sortOrder: z.number().int().optional(),
});

export const updateCharacterSchema = z.object({
  name: z.string().min(1).max(100).optional(),
  aliases: z.string().optional(),
  gender: z.string().optional().nullable(),
  apparentAge: z.number().int().positive().optional().nullable(),
  actualAge: z.number().int().positive().optional().nullable(),
  birthday: z.string().optional().nullable(),
  species: z.string().optional().nullable(),
  nationality: z.string().optional().nullable(),
  occupations: z.string().optional(),
  socialClass: z.string().optional().nullable(),
  characterStatus: z.enum(["ALIVE", "DEAD", "MISSING", "PRESUMED_DEAD"]).optional(),
  height: z.string().optional().nullable(),
  build: z.string().optional().nullable(),
  skinTone: z.string().optional().nullable(),
  hairColor: z.string().optional().nullable(),
  hairStyle: z.string().optional().nullable(),
  eyeColor: z.string().optional().nullable(),
  distinguishingFeatures: z.string().optional().nullable(),
  appearanceDesc: z.string().optional().nullable(),
  personalityType: z.string().optional().nullable(),
  coreTraits: z.string().optional(),
  virtues: z.string().optional(),
  flaws: z.string().optional(),
  moralAlignment: z.string().optional().nullable(),
  childhood: z.string().optional().nullable(),
  familyBackground: z.string().optional().nullable(),
  traumas: z.string().optional(),
  secrets: z.string().optional().nullable(),
  speechDialect: z.string().optional().nullable(),
  catchphrases: z.string().optional(),
  nervousHabits: z.string().optional(),
  hobbies: z.string().optional(),
  arcType: z.string().optional().nullable(),
  arcStartState: z.string().optional().nullable(),
  arcMidpoint: z.string().optional().nullable(),
  arcEndState: z.string().optional().nullable(),
  developmentStatus: z.enum(["CONCEPT", "DEVELOPING", "FLESHED_OUT", "REVISING"]).optional(),
  roleInStory: z.string().optional().nullable(),
  tags: z.string().optional(),
  groups: z.string().optional(),
  importance: z.number().int().min(1).max(10).optional(),
  sortOrder: z.number().int().optional(),
});

export type CreateCharacterInput = z.infer<typeof createCharacterSchema>;
export type UpdateCharacterInput = z.infer<typeof updateCharacterSchema>;
